package lib

/*
#include "lv_init.h"
*/
import "C"

type LV_PALETTE_T = C.lv_palette_t
type LV_COLOR_T = C.lv_color_t
type LV_OPA_T = C.lv_opa_t
type LV_COLOR_HSV_T = C.lv_color_hsv_t
type LV_STYLE_SELECTOR_T = C.lv_style_selector_t
type LV_GRAD_DIR_T = C.lv_grad_dir_t

const (
	LV_PART_MAIN         LV_STYLE_SELECTOR_T = C.LV_PART_MAIN
	LV_PART_SCROLLBAR    LV_STYLE_SELECTOR_T = C.LV_PART_SCROLLBAR
	LV_PART_INDICATOR    LV_STYLE_SELECTOR_T = C.LV_PART_INDICATOR
	LV_PART_KNOB         LV_STYLE_SELECTOR_T = C.LV_PART_KNOB
	LV_PART_SELECTED     LV_STYLE_SELECTOR_T = C.LV_PART_SELECTED
	LV_PART_ITEMS        LV_STYLE_SELECTOR_T = C.LV_PART_ITEMS
	LV_PART_TICKS        LV_STYLE_SELECTOR_T = C.LV_PART_TICKS
	LV_PART_CURSOR       LV_STYLE_SELECTOR_T = C.LV_PART_CURSOR
	LV_PART_CUSTOM_FIRST LV_STYLE_SELECTOR_T = C.LV_PART_CUSTOM_FIRST
	LV_PART_ANY          LV_STYLE_SELECTOR_T = C.LV_PART_ANY
)

const (
	LV_GRAD_DIR_NONE LV_GRAD_DIR_T = C.LV_GRAD_DIR_NONE
	LV_GRAD_DIR_VER  LV_GRAD_DIR_T = C.LV_GRAD_DIR_VER
	LV_GRAD_DIR_HOR  LV_GRAD_DIR_T = C.LV_GRAD_DIR_HOR
)
