package lvgl_go

/*
#include "lv_init.h"
static const int _LV_SIZE_CONTENT = LV_SIZE_CONTENT;
*/
import "C"

type LvObj C.struct__lv_obj_t
type LvSpan C.struct__lv_span_t

const (
	LV_SIZE_CONTENT C.int = C._LV_SIZE_CONTENT

	LV_ALIGN_DEFAULT      C.int = C.LV_ALIGN_DEFAULT
	LV_ALIGN_TOP_LEFT     C.int = C.LV_ALIGN_TOP_LEFT
	LV_ALIGN_TOP_MID      C.int = C.LV_ALIGN_TOP_MID
	LV_ALIGN_TOP_RIGHT    C.int = C.LV_ALIGN_TOP_RIGHT
	LV_ALIGN_BOTTOM_LEFT  C.int = C.LV_ALIGN_BOTTOM_LEFT
	LV_ALIGN_BOTTOM_MID   C.int = C.LV_ALIGN_BOTTOM_MID
	LV_ALIGN_BOTTOM_RIGHT C.int = C.LV_ALIGN_BOTTOM_RIGHT
	LV_ALIGN_LEFT_MID     C.int = C.LV_ALIGN_LEFT_MID
	LV_ALIGN_RIGHT_MID    C.int = C.LV_ALIGN_RIGHT_MID
	LV_ALIGN_CENTER       C.int = C.LV_ALIGN_CENTER

	LV_ALIGN_OUT_TOP_LEFT     C.int = C.LV_ALIGN_OUT_TOP_LEFT
	LV_ALIGN_OUT_TOP_MID      C.int = C.LV_ALIGN_OUT_TOP_MID
	LV_ALIGN_OUT_TOP_RIGHT    C.int = C.LV_ALIGN_OUT_TOP_RIGHT
	LV_ALIGN_OUT_BOTTOM_LEFT  C.int = C.LV_ALIGN_OUT_BOTTOM_LEFT
	LV_ALIGN_OUT_BOTTOM_MID   C.int = C.LV_ALIGN_OUT_BOTTOM_MID
	LV_ALIGN_OUT_BOTTOM_RIGHT C.int = C.LV_ALIGN_OUT_BOTTOM_RIGHT
	LV_ALIGN_OUT_LEFT_TOP     C.int = C.LV_ALIGN_OUT_LEFT_TOP
	LV_ALIGN_OUT_LEFT_MID     C.int = C.LV_ALIGN_OUT_LEFT_MID
	LV_ALIGN_OUT_LEFT_BOTTOM  C.int = C.LV_ALIGN_OUT_LEFT_BOTTOM
	LV_ALIGN_OUT_RIGHT_TOP    C.int = C.LV_ALIGN_OUT_RIGHT_TOP
	LV_ALIGN_OUT_RIGHT_MID    C.int = C.LV_ALIGN_OUT_RIGHT_MID
	LV_ALIGN_OUT_RIGHT_BOTTOM C.int = C.LV_ALIGN_OUT_RIGHT_BOTTOM
)
